name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Print working directory and files (Debugging)
      run: |
        pwd
        ls -R  # List all files to check project structure

    - name: Restore dependencies
      working-directory: Application  # Adjust if necessary
      run: dotnet restore

    - name: Build
      working-directory: Application  # Adjust if necessary
      run: dotnet build --no-restore

    - name: Test
      working-directory: Application  # Adjust if necessary
      run: dotnet test --no-build --verbosity normal
